spring.application.name=kutuphaneapi
spring.datasource.url=jdbc:postgresql://localhost:5432/kutuphane_db

# Kullan?c? ad? ve kurulum esnas?nda belirledi?iniz ?ifre
spring.datasource.username=postgres
spring.datasource.password=1234

# JDBC Driver s?n?f? (Java ile PostgreSQL aras?ndaki köprü)
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate DDL: Java Entity s?n?flar?n?zdaki de?i?ikliklere göre tablolar? otomatik olu?turur/günceller
spring.jpa.hibernate.ddl-auto=update

# Konsolda çal??an SQL sorgular?n? ve format?n? görmek için
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true